name: veegil
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  dio: 4.0.6
  shimmer: 2.0.0
  retrofit: 3.0.1+1
  intl: 0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  build_runner: 2.2.0
  retrofit_generator: 4.0.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
